[mcp_servers.awesome-copilot]
type = "http"
enabled = false
url = "http://localhost:48080/mcp"

[mcp_servers.chrome-devtools-mcp]
type = "stdio"
enabled = false
command = "npx"
args = ["-y", "chrome-devtools-mcp"]

[mcp_servers.codex]
type = "stdio"
enabled = true
command = "npx"
args = ["-y", "codex-mcp-server"]

[mcp_servers.context7]
type = "http"
enabled = true
url = "http://localhost:48082/mcp"

[mcp_servers.everything]
type = "http"
enabled = false
url = "http://localhost:48081/mcp"

[mcp_servers.fetch]
type = "stdio"
enabled = true
command = "uvx"
args = ["mcp-server-fetch", "--ignore-robots-txt"]

[mcp_servers.filesystem]
type = "stdio"
enabled = false
command = "sh"
args = ["-lc", "npx -y @modelcontextprotocol/server-filesystem $HOME/Projects"]

[mcp_servers.git]
type = "stdio"
enabled = true
command = "uvx"
args = ["mcp-server-git"]

[mcp_servers.jetbrains]
type = "stdio"
enabled = true
env = { IJ_MCP_SERVER_PORT = "64342" }
command = "sh"
args = ["-lc", "java -jar $HOME/.config/github-copilot/intellij/mcpserver-stdio-253.29346.138-bundle.jar"]

[mcp_servers.markitdown]
type = "http"
enabled = true
url = "http://localhost:48083/mcp"

[mcp_servers.memory]
type = "stdio"
enabled = true
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

[mcp_servers.playwright]
type = "http"
enabled = false
url = "http://localhost:48084/mcp"

[mcp_servers.ripgrep]
type = "stdio"
enabled = true
command = "npx"
args = ["-y", "mcp-ripgrep"]

[mcp_servers.sequential-thinking]
type = "stdio"
enabled = true
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.serena]
type = "stdio"
enabled = true
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--enable-web-dashboard", "false", "--context", "codex", "--project-from-cwd"]

[mcp_servers.time]
type = "stdio"
enabled = false
env = { LOCAL_TIMEZONE = "Asia/Seoul" }
command = "uvx"
args = ["mcp-server-time"]
